### ISSUE TITLE
TYPO3 v10 compatible ext was displayed as v9.5

### ISSUE THREAD

**Issue by froemken** [TYPO3GmbH/site-intercept#19]
Hello,

I have just pushed EXT:sponsoring which is TYPO3 9.5 and 10.4 compatible. A WebHook calls your interceptor.
In list of interceptor I see that manual was only rendered for TYPO3 version 9.5 (column Support).
A little bit deeper I found EXT:headless which has support for 9.5-10.0. So it works in general.

Daniel Siepmann means it seems to be a problem with our 3 parts used TYPO3 version ^10.4.2. But as long as this version is officially supported it would be nice to support this kind of version, too.

Stefan

**Comment by DanielSiepmann** [comment]
Some more sources:

`composer.json` version constraint of affected extension: https://github.com/jweiland-net/sponsoring/blob/3.0.0/composer.json#L21 `"typo3/cms-core": "^9.5.17 || ^10.4.2",`
The mentioned extension where everything works: https://github.com/TYPO3-Initiatives/headless/blob/v2.2.0/composer.json#L30 `"typo3/cms-core": "^9.5 || ^10.0",`.

As far as I understand the following code is involved inside of intercept: https://github.com/TYPO3GmbH/site-intercept/blob/2.2.1/src/Extractor/ComposerJson.php#L98
