### ISSUE TITLE
Q: How does the current webhook for docs rendering work?

### ISSUE THREAD

**Issue by marble** [TYPO3GmbH/site-intercept#72]
I'd like to understand how we get from the GitHub webhook notification to the rendering and deployment of a manual.

I'm aware of 
* https://github.com/TYPO3-Documentation/t3docs-ci-deploy
* https://github.com/TYPO3-Documentation/gh-render-action

But what's going on when GitHub requests https://docs-hook.typo3.org ?
Which script is behind that?

**Comment by susannemoog** [comment]
Please check out this repository and start reading at https://github.com/TYPO3GmbH/site-intercept/blob/develop/src/Controller/DocsRenderingController.php#L48 - that's the route behind the hook domain.
