### ISSUE TITLE
Mask email addresses when creating new issues

### ISSUE THREAD

**Issue by simonschaufi** [TYPO3GmbH/site-intercept#76]
Email addresses should be masked like `***@typo3.org` to not reveal email addresses to the public which spammers could collect easily since these will be publicly exposed and nobody really likes to get spam emails.

https://stackoverflow.com/questions/20545301/partially-hide-email-address-in-php

**Comment by andreasfernandez** [comment]
I'd like to consult a security researcher on this. I think you refer to the creation of tickets for the documentation team on changelog updates.

The email addresses in there are already publicly available through the git history (and thus Github) anyway.

**Comment by simonschaufi** [comment]
I wouldn't consider a git log as public, because you need to checkout the git repo in order to see the author's email address. GitHub itself hides the email address everywhere in order to protect the users privacy and I expect the same.

**Comment by andreasfernandez** [comment]
The mail addresses are still visible in Gerrit. Anyway, I'll discuss this with the security team.

**Comment by ohader** [comment]
This is rather a data-privacy topic than a security topic. Participating in an open-source community implies, that email addresses are available to the public as well. For instance each Git commit contains these details, and so does the public GitHub API (listing committer, names and email addresses), e.g. https://api.github.com/repos/typo3/typo3/commits/d08605405ab767a851e6205b381e6bcc3cddbe51.

**Comment by simonschaufi** [comment]
Yes I know but look what happens when I reply via email... My email address
gets masked.

**Comment by simonschaufi** [comment]
Yes I know but look what happens when I reply via email... My email address
gets masked.


Am Do., 28. Juli 2022 um 13:40 Uhr schrieb Oliver Hader ***@***.***>:

**Comment by simonschaufi** [comment]
Yes I know but look what happens when I reply via email... Your email address gets masked.

```
                                                         ↓
Am Do., 28. Juli 2022 um 13:40 Uhr schrieb Oliver Hader ***@***.***>:

> ...
>
> Message ID: ***@***.***>
>
```

**Comment by ohader** [comment]
To avoid me misunderstanding the scope, can you please give an example (link, screenshot, ...) where email addresses un question are shown currently? Thx

**Comment by simonschaufi** [comment]
In this repository the GitHub Issue create service is used: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues

**Comment by andreasfernandez** [comment]
Once a commit is pushed to the TYPO3 core repository, the [/create-rst-issue](https://github.com/TYPO3GmbH/site-intercept/blob/develop/src/Controller/GithubRstIssueController.php) endpoint is triggered. The underlying `GithubService` interprets the incoming data and composes the issue for Github.
