### ISSUE TITLE
Make the "create issue from core change" reusable for other projects

### ISSUE THREAD

**Issue by simonschaufi** [TYPO3GmbH/site-intercept#77]
Some other projects could also use this:

- https://github.com/FriendsOfTYPO3/extension_builder
- https://github.com/sabbelasichon/typo3-rector

**Comment by andreasfernandez** [comment]
Hey,

can you please elaborate on what you're referring to?

**Comment by simonschaufi** [comment]
I'm referring to the automatic github issue generation script which is used for the documentation team already.

**Comment by andreasfernandez** [comment]
I see. This is not a simple script than can be stripped off intercept, also it's solely built for that specific use case. I can discuss this internally with the team, but with a lower priority only.

**Comment by simonschaufi** [comment]
@andreaskienast For TYPO3 Rector this would be incredibly useful as we are currently importing the issues manually via a Symfony Application which is not very convenient.

**Comment by simonschaufi** [comment]
@andreaskienast For TYPO3 Rector this would be incredibly useful as we are currently importing the issues manually via a Symfony Application which is not very convenient.
FYI: @sabbelasichon
